# .github/workflows/deploy.yml

name: Deploy React App to GitHub Pages

on:
  # Runs on pushes targeting the default branch (usually 'main')
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # Use the latest version of the checkout action
        uses: actions/checkout@v4

      - name: Set up Node.js
        # Use the latest version of the setup-node action
        uses: actions/setup-node@v4
        with:
          node-version: 18 # A stable, long-term support version of Node.js
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build React App
        # This command creates the 'build' folder with your final website files
        run: npm run build

      - name: Setup Pages
        # Use the latest version of the configure-pages action
        uses: actions/configure-pages@v5

      - name: Upload artifact
        # Use the latest version of the upload-pages-artifact action
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the 'build' folder created in the previous step
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        # Use the latest version of the deploy-pages action
        uses: actions/deploy-pages@v4
